### PR TITLE
Use F# as in TC for operations, bug fixes

### PR DESCRIPTION
**Pull request by johanssondavid**

### CODE REVIEW

**Comment by ripxorip** [comment]
Need updated syntax as well, otherwise golden. Will merge next instead, closing this one.

**Comment by johanssondavid** [comment]
Don't close the pull request. It can be updated with the patch.

**Comment by ripxorip** [comment]
Aight, open!

**Comment by johanssondavid** [comment]
@philip-karlsson have a look now!

**Comment by ripxorip** [comment]
Looks good, merging!

**Pull request merged**
